services:
  - type: web
    name: bookingkoala-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_listener.py
    envVars:
      - key: FLASK_ENV
        value: production